[serve.static]
plugins = [
  "@zomme/bun-plugin-tsr",
  "@zomme/bun-plugin-iconify",
  "@zomme/bun-plugin-i18next",
  "bun-plugin-tailwind",
]

[plugins.tsr]
rootDirectory = "src"
watch = false

[plugins.iconify]
dirs = ["src"]

[plugins.i18next]
dirs = "src"
