apiVersion: v2
name: buntime
description: A Helm chart for Buntime - Worker Pool Runtime for Bun applications
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://bun.sh/logo.svg
keywords:
  - buntime
  - bun
  - runtime
  - worker-pool
  - microservices
home: https://github.com/djalmajr/buntime
sources:
  - https://github.com/djalmajr/buntime
maintainers:
  - name: Djalma JÃºnior
    email: djalmajr@gmail.com
