[serve.static]
plugins = [
  "@zomme/bun-plugin-tsr",
  "@zomme/bun-plugin-iconify",
  "@zomme/bun-plugin-i18next",
  "bun-plugin-tailwind",
]

[plugins.tsr]
rootDirectory = "client"

[plugins.iconify]
dirs = ["client"]

[plugins.i18next]
dirs = "client"

[test]
preload = ["./scripts/test-setup.ts"]
