name: Publish Helm Charts

on:
  push:
    branches: [main]
    paths:
      - "charts/**"
      - ".github/workflows/helm-publish.yml"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout buntime
        uses: actions/checkout@v4

      - name: Push charts to zommehq/charts
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CHARTS_PAT }}
        with:
          source-directory: "charts"
          destination-github-username: "zommehq"
          destination-repository-name: "charts"
          target-directory: "charts"
          target-branch: main
          commit-message: "chore: sync charts from buntime"
